package Interfaces;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
//import net.sf.jasperreports.engine.JRException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Anderson
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    String CI_Lab;
    Conexion con = new Conexion();
    Object[][] data = con.datosExamenes();
    String[] columnas = {"CODIGO", "TIPO", "NOMBRE", "COSTO"};
    DefaultTableModel modelo = new DefaultTableModel(data, columnas) {
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };
    String[] columnasPAC = {"CODIGO", "TIPO", "NOMBRE", "COSTO"};
    DefaultTableModel modeloPac = new DefaultTableModel(null, columnasPAC) {
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    //DefaultTableModel ListaExaPac = new DefaultTableModel();
    public principal() {
        initComponents();
        pnlFondo fondo = new pnlFondo(1366, 768);
        this.add(fondo, BorderLayout.CENTER);
        this.pack();
        fondo.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        CI_Lab = "1805037619";
        //Inhabilidar paneles
        for (Component c : jPanel1.getComponents()) {
            c.setEnabled(false);
        }
        
        //
        //jTableListaExamenesPac.setModel(ListaExaPac);
    }

    public principal(String CI,boolean supUsu) {
        initComponents();
        CI_Lab = CI;
        pnlFondo fondo = new pnlFondo(1366, 768);
        this.add(fondo, BorderLayout.CENTER);
        this.pack();
        fondo.setVisible(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        for (Component c : jPanel1.getComponents()) {
            c.setEnabled(false);
        }
        activarSupUser(supUsu);
        // jTableListaExamenes.setModel(listaExamenes);
        //jTableListaExamenesPac.setModel(ListaExaPac);
    }
    
    public void activarSupUser(boolean es){
        if(es){
            jMenuItemNueExa.setEnabled(true);
            jMenuItemNueLab.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuEliminar = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDialog_Registro_Cliente = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_Nom_cli1 = new javax.swing.JTextField();
        jTextFieldApe_cli1 = new javax.swing.JTextField();
        jTextFieldTel_cli1 = new javax.swing.JTextField();
        jTextFieldCorr_cli = new javax.swing.JTextField();
        jTextFieldDir_cli1 = new javax.swing.JTextField();
        jTextFieldCel_cli1 = new javax.swing.JTextField();
        jTextField1CICliente1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1Guardar = new javax.swing.JButton();
        jButton2Cancealr = new javax.swing.JButton();
        jToolBarHerramientas = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton4NewUser = new javax.swing.JButton();
        jButton5AddUser = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton6Reportes = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jToolBarUsuarios = new javax.swing.JToolBar();
        jLabelNomUSR = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonSalir_TollBar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1CICliente = new javax.swing.JTextField();
        jButton1BUSCAR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Nom_cli = new javax.swing.JTextField();
        jTextFieldApe_cli = new javax.swing.JTextField();
        jTextFieldTel_cli = new javax.swing.JTextField();
        jTextFieldDir_cli = new javax.swing.JTextField();
        jTextFieldCel_cli = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaExamenesPac = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableListaExamenes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextFieldBuscarExamen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButtonEliminarLisPac = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNumConsult = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFecCon = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_Archivo = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemNueExa = new javax.swing.JMenuItem();
        jMenuItemNueLab = new javax.swing.JMenuItem();
        jMenuItemNueCli = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemExaMasFre = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        Facturas = new javax.swing.JMenuItem();

        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuEliminar.add(jMenuItem1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setText("NOMBRE:");

        jLabel7.setText("APELLIDO:");

        jLabel12.setText("FECHA NAC.: ");

        jLabel13.setText("TELÉFONO:");

        jLabel14.setText("CELULAR:");

        jLabel15.setText("CORREO: ");

        jLabel16.setText("DIRECCIÓN:");

        jLabel17.setText("CÉDULA:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1CICliente1)
                            .addComponent(jTextField_Nom_cli1)
                            .addComponent(jTextFieldDir_cli1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jTextFieldCorr_cli, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTel_cli1)
                            .addComponent(jTextFieldCel_cli1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextFieldApe_cli1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1CICliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_Nom_cli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldTel_cli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldCel_cli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldApe_cli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCorr_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldDir_cli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("REGISTRO NUEVO CLIENTE");

        jButton1Guardar.setText("Guardar");
        jButton1Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1GuardarActionPerformed(evt);
            }
        });

        jButton2Cancealr.setText("Cancelar");
        jButton2Cancealr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancealrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog_Registro_ClienteLayout = new javax.swing.GroupLayout(jDialog_Registro_Cliente.getContentPane());
        jDialog_Registro_Cliente.getContentPane().setLayout(jDialog_Registro_ClienteLayout);
        jDialog_Registro_ClienteLayout.setHorizontalGroup(
            jDialog_Registro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_Registro_ClienteLayout.createSequentialGroup()
                .addGroup(jDialog_Registro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog_Registro_ClienteLayout.createSequentialGroup()
                        .addGroup(jDialog_Registro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialog_Registro_ClienteLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel18))
                            .addGroup(jDialog_Registro_ClienteLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog_Registro_ClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1Guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2Cancealr)))
                .addContainerGap())
        );
        jDialog_Registro_ClienteLayout.setVerticalGroup(
            jDialog_Registro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_Registro_ClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialog_Registro_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2Cancealr)
                    .addComponent(jButton1Guardar))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBarHerramientas.setRollover(true);
        jToolBarHerramientas.add(jSeparator3);

        jButton4NewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jButton4NewUser.setFocusable(false);
        jButton4NewUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4NewUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4NewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4NewUserActionPerformed(evt);
            }
        });
        jToolBarHerramientas.add(jButton4NewUser);

        jButton5AddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/useradd.png"))); // NOI18N
        jButton5AddUser.setFocusable(false);
        jButton5AddUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5AddUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5AddUserActionPerformed(evt);
            }
        });
        jToolBarHerramientas.add(jButton5AddUser);
        jToolBarHerramientas.add(jSeparator4);

        jButton6Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        jButton6Reportes.setFocusable(false);
        jButton6Reportes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6Reportes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ReportesActionPerformed(evt);
            }
        });
        jToolBarHerramientas.add(jButton6Reportes);
        jToolBarHerramientas.add(jSeparator5);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medical-history.png"))); // NOI18N
        jButton3.setToolTipText("Entraga de Resultados");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBarHerramientas.add(jButton3);

        jToolBarUsuarios.setRollover(true);

        jLabelNomUSR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNomUSR.setText("Anderson Naranjo");
        jToolBarUsuarios.add(jLabelNomUSR);
        jToolBarUsuarios.add(jSeparator2);

        jButtonSalir_TollBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jButtonSalir_TollBar.setFocusable(false);
        jButtonSalir_TollBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSalir_TollBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSalir_TollBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir_TollBarActionPerformed(evt);
            }
        });
        jToolBarUsuarios.add(jButtonSalir_TollBar);

        jLabel1.setText("CÉDULA: ");

        jTextField1CICliente.setFocusCycleRoot(true);
        jTextField1CICliente.setFocusTraversalPolicyProvider(true);

        jButton1BUSCAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/loupe.png"))); // NOI18N
        jButton1BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BUSCARActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("APELLIDO:");

        jLabel5.setText("TELÉFONO:");

        jLabel6.setText("CELULAR:");

        jLabel8.setText("DIRECCIÓN:");

        jTextField_Nom_cli.setEditable(false);

        jTextFieldApe_cli.setEditable(false);

        jTextFieldTel_cli.setEditable(false);

        jTextFieldDir_cli.setEditable(false);

        jTextFieldCel_cli.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(50, 50, 50)
                                .addComponent(jTextField_Nom_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(44, 44, 44)
                                .addComponent(jTextFieldApe_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTel_cli)
                            .addComponent(jTextFieldCel_cli, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldDir_cli, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_Nom_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldApe_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTel_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldCel_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldDir_cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTableListaExamenesPac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableListaExamenesPac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "TIPO", "NOMBRE", "COSTO"
            }
        ));
        jTableListaExamenesPac.setFillsViewportHeight(true);
        jTableListaExamenesPac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaExamenesPacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaExamenesPac);

        jTableListaExamenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableListaExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODIGO", "TIPO", "NOMBRE", "COSTO"
            }
        ));
        jTableListaExamenes.setFillsViewportHeight(true);
        jTableListaExamenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaExamenesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableListaExamenes);

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldBuscarExamen.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldBuscarExamen.setText("Buscar");
        jTextFieldBuscarExamen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBuscarExamenFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBuscarExamenFocusLost(evt);
            }
        });
        jTextFieldBuscarExamen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBuscarExamenMouseClicked(evt);
            }
        });
        jTextFieldBuscarExamen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarExamenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarExamenKeyTyped(evt);
            }
        });

        jLabel9.setText("TOTAL:");

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonEliminarLisPac.setText("-");
        jButtonEliminarLisPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarLisPacActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CONSULTA:");

        jTextFieldNumConsult.setEditable(false);
        jTextFieldNumConsult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldNumConsult.setEnabled(false);
        jTextFieldNumConsult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumConsultActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("FECHA CONSULTA:");

        jTextFieldFecCon.setEditable(false);
        jTextFieldFecCon.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldFecCon.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFecCon, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldFecCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu_Archivo.setText("Archivo");

        jMenu3.setText("Nuevo");

        jMenuItemNueExa.setText("Examen");
        jMenuItemNueExa.setEnabled(false);
        jMenuItemNueExa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNueExaActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemNueExa);

        jMenuItemNueLab.setText("Laboratorista");
        jMenuItemNueLab.setEnabled(false);
        jMenu3.add(jMenuItemNueLab);

        jMenuItemNueCli.setText("Cliente");
        jMenuItemNueCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNueCliActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemNueCli);

        jMenu_Archivo.add(jMenu3);
        jMenu_Archivo.add(jSeparator1);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu_Archivo.add(jMenuItemSalir);

        jMenuBar1.add(jMenu_Archivo);

        jMenu2.setText("Ver");

        jMenu1.setText("Reportes");

        jMenuItemExaMasFre.setText("Conteo de Examenes");
        jMenuItemExaMasFre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExaMasFreActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExaMasFre);

        jMenuItem2.setText("Examenes Terminado");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Examenes No Terminados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu2.add(jMenu1);

        Facturas.setText("Facturas");
        Facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturasActionPerformed(evt);
            }
        });
        jMenu2.add(Facturas);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBarHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 1149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1CICliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1BUSCAR)
                            .addGap(64, 64, 64)
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldNumConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonEliminarLisPac)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldBuscarExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBarHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToolBarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBuscarExamen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField1CICliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jButton1BUSCAR, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jTextFieldNumConsult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonEliminarLisPac))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
        login log = new login();
        log.setVisible(true);

    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jButtonSalir_TollBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir_TollBarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_jButtonSalir_TollBarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ResultSet res = con.busquedLabo(CI_Lab);
        try {
            while (res.next()) {
                jLabelNomUSR.setText(res.getString(2) + " " + res.getString(3));
            }

        } catch (SQLException ex) {
            Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTableListaExamenes.setModel(modelo);
        jTableListaExamenesPac.setModel(modeloPac);


    }//GEN-LAST:event_formWindowOpened

    private void jButton1BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BUSCARActionPerformed
        // TODO add your handling code here:
        String ci_cli = jTextField1CICliente.getText();
        busquedaLlenadoCliente(ci_cli);

    }//GEN-LAST:event_jButton1BUSCARActionPerformed

    private void busquedaLlenadoCliente(String ci_cli) {
        if (Auxiliar.verificarCedula(ci_cli) == 1) {
            ResultSet res = con.datos_cli(ci_cli);
            try {
                while (res.next()) {
                    String[] edad = res.getString(3).split(" ");
                    jTextField_Nom_cli.setText(res.getString(1));
                    jTextFieldApe_cli.setText(res.getString(2));
                    
                    jTextFieldTel_cli.setText(res.getString(4));
                    jTextFieldCel_cli.setText(res.getString(5));
                    
                    jTextFieldDir_cli.setText(res.getString(7));
                    
                }
                Calendar c = new GregorianCalendar();
                String dia = Integer.toString(c.get(Calendar.DATE));
                String mes = Integer.toString(c.get(Calendar.MONTH));
                String año = Integer.toString(c.get(Calendar.YEAR));
                jTextFieldFecCon.setText(dia + "/" + mes + "/" + año);
                jTableListaExamenes.setEnabled(true);
                jTableListaExamenesPac.setEnabled(true);
                
                int consulta = con.contConsltas() + 1;
                jTextFieldNumConsult.setText(String.valueOf(consulta));
            } catch (SQLException ex) {
                Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            limpiado_Bloqueo();
        }
    }

    private void jButton4NewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4NewUserActionPerformed
        // TODO add your handling code here:
        NewClient dialog = new NewClient(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton4NewUserActionPerformed

    float total = 0;
    private void jTableListaExamenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaExamenesMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 1) {
            // JOptionPane.showMessageDialog(null, "Pulso el izquierdo");
            if (evt.getClickCount() == 2) {
                ingresarExamenSelec();
            }
        } else {
            //JOptionPane.showMessageDialog(null, "Pulso el derecho");

        }

    }//GEN-LAST:event_jTableListaExamenesMouseClicked

    private void ingresarExamenSelec() throws NumberFormatException {
        TableModel mo = jTableListaExamenes.getModel();
        // TableModel mo = (TableModel) tabla.getModel();
        int a = jTableListaExamenes.getSelectedRow();// evento al dar doble clic en la lista de los examenes para trasladarlo a la lista del paciente
        if(a==-1){
            
        }else{
        Object[] d = new Object[4];
        d[0] = mo.getValueAt(a, 0);
        d[1] = mo.getValueAt(a, 1);
        d[2] = mo.getValueAt(a, 2);
        d[3] = mo.getValueAt(a, 3);

        int filPac = jTableListaExamenesPac.getRowCount();
        if (!jTextFieldFecCon.getText().equals("")) {
            if (filPac > 0) {
                TableModel modeloPa = jTableListaExamenesPac.getModel();
                int i;
                for (i = 0; i < filPac; i++) {
                    String aux = modeloPa.getValueAt(i, 0).toString();

                    if (aux == d[0].toString()) {
                        break;
                    }
                }
                if (i == (filPac)) {
                    total = total + Float.valueOf(d[3].toString());
                    jTextFieldTotal.setText(String.valueOf(total));
                    modeloPac.addRow(d);
                    jTableListaExamenesPac.setModel(modeloPac);
                }

            } else {
                total = total + Float.valueOf(d[3].toString());
                jTextFieldTotal.setText(String.valueOf(total));
                modeloPac.addRow(d);
                jTableListaExamenesPac.setModel(modeloPac);
            }
        }
    
        }
        //JOptionPane.showMessageDialog(this, modelo.getValueAt(a, 0).toString());
        
    }
    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ingresarExamenSelec();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5AddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5AddUserActionPerformed
        // TODO add your handling code here:
//        EditClient dialog = new EditClient(new javax.swing.JFrame(), true);
//        dialog.setVisible(true);

    }//GEN-LAST:event_jButton5AddUserActionPerformed

    private void jTextFieldBuscarExamenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBuscarExamenMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jTextFieldBuscarExamenMouseClicked

    private void jTextFieldBuscarExamenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBuscarExamenFocusGained
        // TODO add your handling code here:
        jTextFieldBuscarExamen.setForeground(Color.BLACK);
        jTextFieldBuscarExamen.setText("");
    }//GEN-LAST:event_jTextFieldBuscarExamenFocusGained

    private void jTextFieldBuscarExamenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBuscarExamenFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldBuscarExamenFocusLost
    private TableRowSorter tabla;

    public void filtro() {
        tabla.setRowFilter(RowFilter.regexFilter(jTextFieldBuscarExamen.getText(), 2));
    }
    private void jTextFieldBuscarExamenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarExamenKeyTyped
        // TODO add your handling code here: 
        jTextFieldBuscarExamen.addKeyListener(new KeyAdapter() {

            public void keyReleased(final KeyEvent e) {
                String Cadena = jTextFieldBuscarExamen.getText().trim();
                jTextFieldBuscarExamen.setText(Cadena);
                repaint();
                filtro();
                
                          

            }
        });

        tabla = new TableRowSorter(modelo);

        jTableListaExamenes.setRowSorter(tabla);


    }//GEN-LAST:event_jTextFieldBuscarExamenKeyTyped

    private void jTextFieldBuscarExamenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarExamenKeyReleased
        // TODO add your handling code here:busqueda de examenes
//        if(jTextFieldBuscarExamen.getText().equals("")){
//            
//        }else{
//            int a= modelo.getRowCount()-1;
//          //  JOptionPane.showMessageDialog(this, a);
//          if(a>0){
//          for (int i = a; i >= 0; i--) {
//                modelo.removeRow(modelo.getRowCount()-1);
//                               
//            }    
//          } 
//          
//            ResultSet res = con.busquedaExamen(jTextFieldBuscarExamen.getText());
//            
//            try {
//                while(res.next()){
//                   Object[] op= new Object[4];
//                   op[0]=res.getString(1);
//                   op[1]=res.getString(2);
//                   op[2]=res.getString(3);
//                   op[3]=res.getString(4);
//                   modelo.addRow(op);
//                }              
//            } catch (SQLException ex) {
//                JOptionPane.showMessageDialog(this, ex.getMessage());
//            }
//             conEl++;  

        // TableRowSorter tabla= new TableRowSorter(modelo) ;
        //   }

    }//GEN-LAST:event_jTextFieldBuscarExamenKeyReleased

    private void jTableListaExamenesPacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaExamenesPacMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 1) {
            // JOptionPane.showMessageDialog(null, "Pulso el izquierdo");
        } else if (evt.getButton() == 2) {
            //JOptionPane.showMessageDialog(null, "Pulso el central");
        } else if (evt.getButton() == 3) {
            //JOptionPane.showMessageDialog(null, "Pulso el derecho");
            menuEliminar.show(jTableListaExamenesPac, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jTableListaExamenesPacMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        eliminarListaPac();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonEliminarLisPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarLisPacActionPerformed
        // TODO add your handling code here:
        eliminarListaPac();
    }//GEN-LAST:event_jButtonEliminarLisPacActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        if (jTextFieldTotal.getText().equals("") || jTextFieldFecCon.getText().equals("") || jTextFieldTotal.getText().equals("0.0")) {

        } else {
            String[] datos = new String[4];
            datos[0] = jTextFieldNumConsult.getText();
            datos[1] = jTextField1CICliente.getText();
            datos[2] = CI_Lab;
            datos[3] = jTextFieldFecCon.getText();

            TableModel modeloPa = jTableListaExamenesPac.getModel();
            int filPac = jTableListaExamenesPac.getRowCount();
            String[] examenes = new String[filPac];
            int i;
            for (i = 0; i < filPac; i++) {
                examenes[i] = modeloPa.getValueAt(i, 0).toString();
            }
            con.insertarConsulta(datos, examenes);

            limpiado_Bloqueo();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ReportesActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jButton6ReportesActionPerformed
public boolean ValidarControlesIngreso(){
        if("".equals(jTextField1CICliente1.getText())|| Auxiliar.verificarCedula(jTextField1CICliente1.getText())==0){//|| Auxiliar.verificarCedula(jTextField1CICliente1.getText())==1){
            JOptionPane.showMessageDialog(this,"Ingrese Cédula Correcta");
            return false;
        }
        if("".equals(jTextField_Nom_cli.getText())){
            JOptionPane.showMessageDialog(this, "Ingrese Nombre ");
            return false;
        }
        if("".equals(jTextFieldApe_cli.getText())){
            JOptionPane.showMessageDialog(this, "Ingrese Apellido ");
            return false;
        }
//        if((jDateChooserFec_nac.getDate())== null){
//            JOptionPane.showMessageDialog(this, "Ingrese Fecha ");
//            return false;
//        }
        return true;
    }
    private void jButton1GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1GuardarActionPerformed
//        if(ValidarControlesIngreso()){
//            String[] datos=new String[8];
//            datos[0]=jTextField1CICliente1.getText().toUpperCase();
//            datos[1]=jTextField_Nom_cli.getText().toUpperCase();
//            datos[2]=jTextFieldApe_cli.getText().toUpperCase();
//
//            datos[4]=jTextFieldTel_cli.getText().toUpperCase();
//            datos[5]=jTextFieldCel_cli.getText().toUpperCase();
//            datos[6]=jTextFieldCorr_cli.getText().toUpperCase();
//            datos[7]=jTextFieldDir_cli.getText().toUpperCase();
//
//            /////////////
//            String dia="";
//            String mes="";
//            if(jDateChooserFec_nac.getDate().getDate()<9){
//                dia="0"+String.valueOf(jDateChooserFec_nac.getDate().getDate());
//            }else{
//                dia=String.valueOf(jDateChooserFec_nac.getDate().getDate());
//            }
//            if((jDateChooserFec_nac.getDate().getMonth()+1)<9){
//                mes="0"+String.valueOf(jDateChooserFec_nac.getDate().getMonth()+1);
//            }else{
//                mes=String.valueOf(jDateChooserFec_nac.getDate().getMonth()+1);
//            }
//
//            String año = String.valueOf(jDateChooserFec_nac.getDate().getYear()+1900);
//            //jTextField_Edad_Dem.setText(año);
//            String fec=dia+"/"+mes+"/"+año;
//            datos[3]=fec;
//            if (con.insertarUsuario(datos)) {
//             JOptionPane.showMessageDialog(this, "Registro Exitoso");
//            jTextField1CICliente.setText(datos[0]);
//            busquedaLlenadoCliente(datos[0]);
//            jDialog_Registro_Cliente.setVisible(false);   
//            }else{
//                JOptionPane.showMessageDialog(this, "Fallo en la insercion del Usurio");
//            }
//
//        };
    }//GEN-LAST:event_jButton1GuardarActionPerformed

    private void jButton2CancealrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancealrActionPerformed
        jDialog_Registro_Cliente.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2CancealrActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        LlenadoResultados dialog = new LlenadoResultados(new javax.swing.JFrame(), false);
//        dialog.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItemNueExaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNueExaActionPerformed
        // TODO add your handling code here:
//        NewExamen dialog = new NewExamen(new javax.swing.JFrame(), false);
//        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemNueExaActionPerformed

    private void jMenuItemNueCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNueCliActionPerformed
        // TODO add your handling code here:
//         NewClient dialog = new NewClient(new javax.swing.JFrame(), true);
//        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemNueCliActionPerformed

    private void jMenuItemExaMasFreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExaMasFreActionPerformed
//        try {
//            // TODO add your handling code here:
//            con.abrirRepor("EXAMENES.jrxml");
//        } catch (SQLException ex) {
//           JOptionPane.showMessageDialog(this, ex.getMessage());
//        } catch (JRException ex) {
//           JOptionPane.showMessageDialog(this, ex.getMessage());
//        }
    }//GEN-LAST:event_jMenuItemExaMasFreActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            con.abrirRepor("examenesTerminados.jrxml");
//        } catch (SQLException ex) {
//           JOptionPane.showMessageDialog(this, ex.getMessage());
//        } catch (JRException ex) {
//           JOptionPane.showMessageDialog(this, ex.getMessage());
//        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            con.abrirRepor("examenesNoTerminados.jrxml");
//        } catch (SQLException ex) {
//           JOptionPane.showMessageDialog(this, ex.getMessage());
//        } catch (JRException ex) {
//           JOptionPane.showMessageDialog(this, ex.getMessage());
//        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void FacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturasActionPerformed
        // TODO add your handling code here:
//        ImprecionExamenes dialog = new ImprecionExamenes(new javax.swing.JFrame(), false);
//         dialog.setVisible(true);
    }//GEN-LAST:event_FacturasActionPerformed

    private void jTextFieldNumConsultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumConsultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumConsultActionPerformed

    private void limpiado_Bloqueo() {
        ////////////////////////////////77
        int fil = modeloPac.getRowCount() - 1;
        //  Limpiado del jTable de paciente
        if (fil > 0) {
            for (int j = fil; j >= 0; j--) {
                modeloPac.removeRow(modeloPac.getRowCount() - 1);

            }
        }
        //limpiado de los jTextFiel

        jTextField1CICliente.setText("");
        jTextField_Nom_cli.setText("");
        jTextFieldApe_cli.setText("");

        jTextFieldTel_cli.setText("");
        jTextFieldCel_cli.setText("");
        jTextFieldNumConsult.setText("");
        jTextFieldDir_cli.setText("");
        jTextFieldTotal.setText("");
        jTextFieldFecCon.setText("");
        total = 0;
        jTableListaExamenesPac.setEnabled(false);
        jTableListaExamenes.setEnabled(false);
        //jTextFieldBuscarExamen.setEnabled(false);

        ///////////////////////////////////7
    }

    private void eliminarListaPac() throws NumberFormatException {
        // TODO add your handling code here:
        TableModel modelo = jTableListaExamenesPac.getModel();
        int a = jTableListaExamenesPac.getSelectedRow();
        if (a == -1) {

        } else {

            float cos = Float.valueOf(modelo.getValueAt(a, 3).toString());
            total = total - cos;
            jTextFieldTotal.setText(String.valueOf(total));
            modeloPac.removeRow(a);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Facturas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1BUSCAR;
    private javax.swing.JButton jButton1Guardar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton2Cancealr;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4NewUser;
    private javax.swing.JButton jButton5AddUser;
    private javax.swing.JButton jButton6Reportes;
    private javax.swing.JButton jButtonEliminarLisPac;
    private javax.swing.JButton jButtonSalir_TollBar;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog_Registro_Cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNomUSR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemExaMasFre;
    private javax.swing.JMenuItem jMenuItemNueCli;
    private javax.swing.JMenuItem jMenuItemNueExa;
    private javax.swing.JMenuItem jMenuItemNueLab;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenu_Archivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JTable jTableListaExamenes;
    private javax.swing.JTable jTableListaExamenesPac;
    private javax.swing.JTextField jTextField1CICliente;
    private javax.swing.JTextField jTextField1CICliente1;
    private javax.swing.JTextField jTextFieldApe_cli;
    private javax.swing.JTextField jTextFieldApe_cli1;
    private javax.swing.JTextField jTextFieldBuscarExamen;
    private javax.swing.JTextField jTextFieldCel_cli;
    private javax.swing.JTextField jTextFieldCel_cli1;
    private javax.swing.JTextField jTextFieldCorr_cli;
    private javax.swing.JTextField jTextFieldDir_cli;
    private javax.swing.JTextField jTextFieldDir_cli1;
    private javax.swing.JTextField jTextFieldFecCon;
    private javax.swing.JTextField jTextFieldNumConsult;
    private javax.swing.JTextField jTextFieldTel_cli;
    private javax.swing.JTextField jTextFieldTel_cli1;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextField_Nom_cli;
    private javax.swing.JTextField jTextField_Nom_cli1;
    private javax.swing.JToolBar jToolBarHerramientas;
    private javax.swing.JToolBar jToolBarUsuarios;
    private javax.swing.JPopupMenu menuEliminar;
    // End of variables declaration//GEN-END:variables
}
